name: Phase One IIQ to Tiff conversion

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create build dir
      run: mkdir build
    - name: run cmake
      run: cd build && cmake ..
    - name: cmake build
      run: cd build && cmake --build .
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r SensorProfiles.zip build/SensorProfiles
    - name: Upload Assets
      uses: actions/upload-artifact@v3
      with:
          name: files
          path: |
            build/SensorProfiles
            build/conversion
            build/SensorProfiles.zip
