name: Phase One IIQ to Tiff conversion

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create build dir
      run: mkdir build
    - name: run cmake
      run: cd build && cmake ..
    - name: cmake build
      run: cd build && cmake --build .
    - name: Create Github release
      id: create_release
      uses: actions/create-release@v1
      with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
              Changes in this release:
              # ${{ env.GIT_HISTORY }}
          draft: false
          prerelease: false
    - name: Upload Assets
      uses: actions/upload-artifact@v2
      with:
          name: assets-for-download
          path: build/conversion
