name: Phase One IIQ to Tiff conversion

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create build dir
      run: mkdir build
    - name: cd to build dir
      run: cd build
    - name: run cmake
      run: cmake ..
    - name: cmake build
      run: cmake --build .
