# Name of the workflow
name: Release

# Run on every commit tag which begins with "v" (e.g., "v0.1.4")
on:
  push:
    tags:
      - "v*"

# Automatically create a GitHub Release, with release details specified (the relevant commits)
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Create build dir
        run: mkdir build
      - name: run cmake
        run: cd build && cmake ..
      - name: cmake build
        run: cd build && cmake --build .
      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip output
        run: zip -qq -r SensorProfiles.zip SensorProfiles
        working-directory: build/

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/SensorProfiles.zip
            build/SensorProfiles
            build/conversion