# Name of the workflow
name: Release

# Run on every commit tag which begins with "v" (e.g., "v0.1.4")
on:
  push:
    tags:
      - "v*"

# Automatically create a GitHub Release, with release details specified (the relevant commits)
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Create build dir
        run: mkdir build
      - name: run cmake
        run: cd build && cmake ..
      - name: cmake build
        run: cd build && cmake --build .
      - name: Upload Assets
        uses: actions/upload-artifact@v3
        with:
            name: files
            path: |
              build/SensorProfiles
              build/conversion